# Generated by Django 2.0.3 on 2019-10-07 06:01

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('placement', jsonfield.fields.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Profile')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.AlterModelOptions(
            name='dinnerplatters',
            options={'verbose_name_plural': 'DinnerPlatters'},
        ),
        migrations.AlterModelOptions(
            name='pasta',
            options={'verbose_name_plural': 'Pasta'},
        ),
        migrations.AlterModelOptions(
            name='salads',
            options={'verbose_name_plural': 'Salads'},
        ),
        migrations.AlterModelOptions(
            name='subs',
            options={'verbose_name_plural': 'Subs'},
        ),
        migrations.AlterModelOptions(
            name='toppings',
            options={'verbose_name_plural': 'Toppings'},
        ),
    ]
